// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ldTfg571hK9WgGgLtdG04FwFEZzXa9A',
    appId: '1:99622899694:web:cda6f438042c73bdf988ff',
    messagingSenderId: '99622899694',
    projectId: 'shalfie',
    authDomain: 'shalfie.firebaseapp.com',
    storageBucket: 'shalfie.firebasestorage.app',
    measurementId: 'G-Z8NF0QJ2QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLTXFbmPKfK3MOwXQf1WduqLdDnvmamEU',
    appId: '1:99622899694:android:dbe5444efe939ab2f988ff',
    messagingSenderId: '99622899694',
    projectId: 'shalfie',
    storageBucket: 'shalfie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjvo5dVJ6j4lWRQbqjHzOboW9jdI0vbAE',
    appId: '1:99622899694:ios:9b1c0ec6545a3e19f988ff',
    messagingSenderId: '99622899694',
    projectId: 'shalfie',
    storageBucket: 'shalfie.firebasestorage.app',
    iosBundleId: 'com.example.shalfie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjvo5dVJ6j4lWRQbqjHzOboW9jdI0vbAE',
    appId: '1:99622899694:ios:9b1c0ec6545a3e19f988ff',
    messagingSenderId: '99622899694',
    projectId: 'shalfie',
    storageBucket: 'shalfie.firebasestorage.app',
    iosBundleId: 'com.example.shalfie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5ldTfg571hK9WgGgLtdG04FwFEZzXa9A',
    appId: '1:99622899694:web:2cc844190218340af988ff',
    messagingSenderId: '99622899694',
    projectId: 'shalfie',
    authDomain: 'shalfie.firebaseapp.com',
    storageBucket: 'shalfie.firebasestorage.app',
    measurementId: 'G-RST427SJ8P',
  );
}
